//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace PhoneApp1.OwlSecureServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToDoItem", Namespace="http://schemas.datacontract.org/2004/07/OwlSecureWebService.Model")]
    public partial class ToDoItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PhoneApp1.OwlSecureServiceReference.ToDoCategory CategoryField;
        
        private bool IsCompleteField;
        
        private string ItemNameField;
        
        private int ToDoItemIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PhoneApp1.OwlSecureServiceReference.ToDoCategory Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsComplete {
            get {
                return this.IsCompleteField;
            }
            set {
                if ((this.IsCompleteField.Equals(value) != true)) {
                    this.IsCompleteField = value;
                    this.RaisePropertyChanged("IsComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToDoItemId {
            get {
                return this.ToDoItemIdField;
            }
            set {
                if ((this.ToDoItemIdField.Equals(value) != true)) {
                    this.ToDoItemIdField = value;
                    this.RaisePropertyChanged("ToDoItemId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToDoCategory", Namespace="http://schemas.datacontract.org/2004/07/OwlSecureWebService.Model")]
    public partial class ToDoCategory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string NameField;
        
        private System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoItem> ToDosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoItem> ToDos {
            get {
                return this.ToDosField;
            }
            set {
                if ((object.ReferenceEquals(this.ToDosField, value) != true)) {
                    this.ToDosField = value;
                    this.RaisePropertyChanged("ToDos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OwlSecureServiceReference.IWCFService")]
    public interface IWCFService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWCFService/DBInitialize", ReplyAction="http://tempuri.org/IWCFService/DBInitializeResponse")]
        System.IAsyncResult BeginDBInitialize(System.AsyncCallback callback, object asyncState);
        
        void EndDBInitialize(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWCFService/LoadAllItemFromDatabase", ReplyAction="http://tempuri.org/IWCFService/LoadAllItemFromDatabaseResponse")]
        System.IAsyncResult BeginLoadAllItemFromDatabase(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoItem> EndLoadAllItemFromDatabase(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWCFService/LoadAllCategoryFromDatabase", ReplyAction="http://tempuri.org/IWCFService/LoadAllCategoryFromDatabaseResponse")]
        System.IAsyncResult BeginLoadAllCategoryFromDatabase(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoCategory> EndLoadAllCategoryFromDatabase(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWCFService/DeleteToDoItem", ReplyAction="http://tempuri.org/IWCFService/DeleteToDoItemResponse")]
        System.IAsyncResult BeginDeleteToDoItem(PhoneApp1.OwlSecureServiceReference.ToDoItem toDoForDelete, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteToDoItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWCFService/AddToDoItem", ReplyAction="http://tempuri.org/IWCFService/AddToDoItemResponse")]
        System.IAsyncResult BeginAddToDoItem(PhoneApp1.OwlSecureServiceReference.ToDoItem newToDoItem, System.AsyncCallback callback, object asyncState);
        
        void EndAddToDoItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWCFService/SaveChangesToDB", ReplyAction="http://tempuri.org/IWCFService/SaveChangesToDBResponse")]
        System.IAsyncResult BeginSaveChangesToDB(System.AsyncCallback callback, object asyncState);
        
        void EndSaveChangesToDB(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceChannel : PhoneApp1.OwlSecureServiceReference.IWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoadAllItemFromDatabaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoadAllItemFromDatabaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoItem> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoItem>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoadAllCategoryFromDatabaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoadAllCategoryFromDatabaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoCategory> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoCategory>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFServiceClient : System.ServiceModel.ClientBase<PhoneApp1.OwlSecureServiceReference.IWCFService>, PhoneApp1.OwlSecureServiceReference.IWCFService {
        
        private BeginOperationDelegate onBeginDBInitializeDelegate;
        
        private EndOperationDelegate onEndDBInitializeDelegate;
        
        private System.Threading.SendOrPostCallback onDBInitializeCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoadAllItemFromDatabaseDelegate;
        
        private EndOperationDelegate onEndLoadAllItemFromDatabaseDelegate;
        
        private System.Threading.SendOrPostCallback onLoadAllItemFromDatabaseCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoadAllCategoryFromDatabaseDelegate;
        
        private EndOperationDelegate onEndLoadAllCategoryFromDatabaseDelegate;
        
        private System.Threading.SendOrPostCallback onLoadAllCategoryFromDatabaseCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteToDoItemDelegate;
        
        private EndOperationDelegate onEndDeleteToDoItemDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteToDoItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddToDoItemDelegate;
        
        private EndOperationDelegate onEndAddToDoItemDelegate;
        
        private System.Threading.SendOrPostCallback onAddToDoItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveChangesToDBDelegate;
        
        private EndOperationDelegate onEndSaveChangesToDBDelegate;
        
        private System.Threading.SendOrPostCallback onSaveChangesToDBCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WCFServiceClient() {
        }
        
        public WCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DBInitializeCompleted;
        
        public event System.EventHandler<LoadAllItemFromDatabaseCompletedEventArgs> LoadAllItemFromDatabaseCompleted;
        
        public event System.EventHandler<LoadAllCategoryFromDatabaseCompletedEventArgs> LoadAllCategoryFromDatabaseCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteToDoItemCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddToDoItemCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SaveChangesToDBCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.OwlSecureServiceReference.IWCFService.BeginDBInitialize(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDBInitialize(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PhoneApp1.OwlSecureServiceReference.IWCFService.EndDBInitialize(System.IAsyncResult result) {
            base.Channel.EndDBInitialize(result);
        }
        
        private System.IAsyncResult OnBeginDBInitialize(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneApp1.OwlSecureServiceReference.IWCFService)(this)).BeginDBInitialize(callback, asyncState);
        }
        
        private object[] OnEndDBInitialize(System.IAsyncResult result) {
            ((PhoneApp1.OwlSecureServiceReference.IWCFService)(this)).EndDBInitialize(result);
            return null;
        }
        
        private void OnDBInitializeCompleted(object state) {
            if ((this.DBInitializeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DBInitializeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DBInitializeAsync() {
            this.DBInitializeAsync(null);
        }
        
        public void DBInitializeAsync(object userState) {
            if ((this.onBeginDBInitializeDelegate == null)) {
                this.onBeginDBInitializeDelegate = new BeginOperationDelegate(this.OnBeginDBInitialize);
            }
            if ((this.onEndDBInitializeDelegate == null)) {
                this.onEndDBInitializeDelegate = new EndOperationDelegate(this.OnEndDBInitialize);
            }
            if ((this.onDBInitializeCompletedDelegate == null)) {
                this.onDBInitializeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDBInitializeCompleted);
            }
            base.InvokeAsync(this.onBeginDBInitializeDelegate, null, this.onEndDBInitializeDelegate, this.onDBInitializeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.OwlSecureServiceReference.IWCFService.BeginLoadAllItemFromDatabase(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoadAllItemFromDatabase(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoItem> PhoneApp1.OwlSecureServiceReference.IWCFService.EndLoadAllItemFromDatabase(System.IAsyncResult result) {
            return base.Channel.EndLoadAllItemFromDatabase(result);
        }
        
        private System.IAsyncResult OnBeginLoadAllItemFromDatabase(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneApp1.OwlSecureServiceReference.IWCFService)(this)).BeginLoadAllItemFromDatabase(callback, asyncState);
        }
        
        private object[] OnEndLoadAllItemFromDatabase(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoItem> retVal = ((PhoneApp1.OwlSecureServiceReference.IWCFService)(this)).EndLoadAllItemFromDatabase(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoadAllItemFromDatabaseCompleted(object state) {
            if ((this.LoadAllItemFromDatabaseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoadAllItemFromDatabaseCompleted(this, new LoadAllItemFromDatabaseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoadAllItemFromDatabaseAsync() {
            this.LoadAllItemFromDatabaseAsync(null);
        }
        
        public void LoadAllItemFromDatabaseAsync(object userState) {
            if ((this.onBeginLoadAllItemFromDatabaseDelegate == null)) {
                this.onBeginLoadAllItemFromDatabaseDelegate = new BeginOperationDelegate(this.OnBeginLoadAllItemFromDatabase);
            }
            if ((this.onEndLoadAllItemFromDatabaseDelegate == null)) {
                this.onEndLoadAllItemFromDatabaseDelegate = new EndOperationDelegate(this.OnEndLoadAllItemFromDatabase);
            }
            if ((this.onLoadAllItemFromDatabaseCompletedDelegate == null)) {
                this.onLoadAllItemFromDatabaseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoadAllItemFromDatabaseCompleted);
            }
            base.InvokeAsync(this.onBeginLoadAllItemFromDatabaseDelegate, null, this.onEndLoadAllItemFromDatabaseDelegate, this.onLoadAllItemFromDatabaseCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.OwlSecureServiceReference.IWCFService.BeginLoadAllCategoryFromDatabase(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoadAllCategoryFromDatabase(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoCategory> PhoneApp1.OwlSecureServiceReference.IWCFService.EndLoadAllCategoryFromDatabase(System.IAsyncResult result) {
            return base.Channel.EndLoadAllCategoryFromDatabase(result);
        }
        
        private System.IAsyncResult OnBeginLoadAllCategoryFromDatabase(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneApp1.OwlSecureServiceReference.IWCFService)(this)).BeginLoadAllCategoryFromDatabase(callback, asyncState);
        }
        
        private object[] OnEndLoadAllCategoryFromDatabase(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoCategory> retVal = ((PhoneApp1.OwlSecureServiceReference.IWCFService)(this)).EndLoadAllCategoryFromDatabase(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoadAllCategoryFromDatabaseCompleted(object state) {
            if ((this.LoadAllCategoryFromDatabaseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoadAllCategoryFromDatabaseCompleted(this, new LoadAllCategoryFromDatabaseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoadAllCategoryFromDatabaseAsync() {
            this.LoadAllCategoryFromDatabaseAsync(null);
        }
        
        public void LoadAllCategoryFromDatabaseAsync(object userState) {
            if ((this.onBeginLoadAllCategoryFromDatabaseDelegate == null)) {
                this.onBeginLoadAllCategoryFromDatabaseDelegate = new BeginOperationDelegate(this.OnBeginLoadAllCategoryFromDatabase);
            }
            if ((this.onEndLoadAllCategoryFromDatabaseDelegate == null)) {
                this.onEndLoadAllCategoryFromDatabaseDelegate = new EndOperationDelegate(this.OnEndLoadAllCategoryFromDatabase);
            }
            if ((this.onLoadAllCategoryFromDatabaseCompletedDelegate == null)) {
                this.onLoadAllCategoryFromDatabaseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoadAllCategoryFromDatabaseCompleted);
            }
            base.InvokeAsync(this.onBeginLoadAllCategoryFromDatabaseDelegate, null, this.onEndLoadAllCategoryFromDatabaseDelegate, this.onLoadAllCategoryFromDatabaseCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.OwlSecureServiceReference.IWCFService.BeginDeleteToDoItem(PhoneApp1.OwlSecureServiceReference.ToDoItem toDoForDelete, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteToDoItem(toDoForDelete, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PhoneApp1.OwlSecureServiceReference.IWCFService.EndDeleteToDoItem(System.IAsyncResult result) {
            base.Channel.EndDeleteToDoItem(result);
        }
        
        private System.IAsyncResult OnBeginDeleteToDoItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PhoneApp1.OwlSecureServiceReference.ToDoItem toDoForDelete = ((PhoneApp1.OwlSecureServiceReference.ToDoItem)(inValues[0]));
            return ((PhoneApp1.OwlSecureServiceReference.IWCFService)(this)).BeginDeleteToDoItem(toDoForDelete, callback, asyncState);
        }
        
        private object[] OnEndDeleteToDoItem(System.IAsyncResult result) {
            ((PhoneApp1.OwlSecureServiceReference.IWCFService)(this)).EndDeleteToDoItem(result);
            return null;
        }
        
        private void OnDeleteToDoItemCompleted(object state) {
            if ((this.DeleteToDoItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteToDoItemCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteToDoItemAsync(PhoneApp1.OwlSecureServiceReference.ToDoItem toDoForDelete) {
            this.DeleteToDoItemAsync(toDoForDelete, null);
        }
        
        public void DeleteToDoItemAsync(PhoneApp1.OwlSecureServiceReference.ToDoItem toDoForDelete, object userState) {
            if ((this.onBeginDeleteToDoItemDelegate == null)) {
                this.onBeginDeleteToDoItemDelegate = new BeginOperationDelegate(this.OnBeginDeleteToDoItem);
            }
            if ((this.onEndDeleteToDoItemDelegate == null)) {
                this.onEndDeleteToDoItemDelegate = new EndOperationDelegate(this.OnEndDeleteToDoItem);
            }
            if ((this.onDeleteToDoItemCompletedDelegate == null)) {
                this.onDeleteToDoItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteToDoItemCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteToDoItemDelegate, new object[] {
                        toDoForDelete}, this.onEndDeleteToDoItemDelegate, this.onDeleteToDoItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.OwlSecureServiceReference.IWCFService.BeginAddToDoItem(PhoneApp1.OwlSecureServiceReference.ToDoItem newToDoItem, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddToDoItem(newToDoItem, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PhoneApp1.OwlSecureServiceReference.IWCFService.EndAddToDoItem(System.IAsyncResult result) {
            base.Channel.EndAddToDoItem(result);
        }
        
        private System.IAsyncResult OnBeginAddToDoItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PhoneApp1.OwlSecureServiceReference.ToDoItem newToDoItem = ((PhoneApp1.OwlSecureServiceReference.ToDoItem)(inValues[0]));
            return ((PhoneApp1.OwlSecureServiceReference.IWCFService)(this)).BeginAddToDoItem(newToDoItem, callback, asyncState);
        }
        
        private object[] OnEndAddToDoItem(System.IAsyncResult result) {
            ((PhoneApp1.OwlSecureServiceReference.IWCFService)(this)).EndAddToDoItem(result);
            return null;
        }
        
        private void OnAddToDoItemCompleted(object state) {
            if ((this.AddToDoItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddToDoItemCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddToDoItemAsync(PhoneApp1.OwlSecureServiceReference.ToDoItem newToDoItem) {
            this.AddToDoItemAsync(newToDoItem, null);
        }
        
        public void AddToDoItemAsync(PhoneApp1.OwlSecureServiceReference.ToDoItem newToDoItem, object userState) {
            if ((this.onBeginAddToDoItemDelegate == null)) {
                this.onBeginAddToDoItemDelegate = new BeginOperationDelegate(this.OnBeginAddToDoItem);
            }
            if ((this.onEndAddToDoItemDelegate == null)) {
                this.onEndAddToDoItemDelegate = new EndOperationDelegate(this.OnEndAddToDoItem);
            }
            if ((this.onAddToDoItemCompletedDelegate == null)) {
                this.onAddToDoItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddToDoItemCompleted);
            }
            base.InvokeAsync(this.onBeginAddToDoItemDelegate, new object[] {
                        newToDoItem}, this.onEndAddToDoItemDelegate, this.onAddToDoItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.OwlSecureServiceReference.IWCFService.BeginSaveChangesToDB(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveChangesToDB(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PhoneApp1.OwlSecureServiceReference.IWCFService.EndSaveChangesToDB(System.IAsyncResult result) {
            base.Channel.EndSaveChangesToDB(result);
        }
        
        private System.IAsyncResult OnBeginSaveChangesToDB(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneApp1.OwlSecureServiceReference.IWCFService)(this)).BeginSaveChangesToDB(callback, asyncState);
        }
        
        private object[] OnEndSaveChangesToDB(System.IAsyncResult result) {
            ((PhoneApp1.OwlSecureServiceReference.IWCFService)(this)).EndSaveChangesToDB(result);
            return null;
        }
        
        private void OnSaveChangesToDBCompleted(object state) {
            if ((this.SaveChangesToDBCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveChangesToDBCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveChangesToDBAsync() {
            this.SaveChangesToDBAsync(null);
        }
        
        public void SaveChangesToDBAsync(object userState) {
            if ((this.onBeginSaveChangesToDBDelegate == null)) {
                this.onBeginSaveChangesToDBDelegate = new BeginOperationDelegate(this.OnBeginSaveChangesToDB);
            }
            if ((this.onEndSaveChangesToDBDelegate == null)) {
                this.onEndSaveChangesToDBDelegate = new EndOperationDelegate(this.OnEndSaveChangesToDB);
            }
            if ((this.onSaveChangesToDBCompletedDelegate == null)) {
                this.onSaveChangesToDBCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveChangesToDBCompleted);
            }
            base.InvokeAsync(this.onBeginSaveChangesToDBDelegate, null, this.onEndSaveChangesToDBDelegate, this.onSaveChangesToDBCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PhoneApp1.OwlSecureServiceReference.IWCFService CreateChannel() {
            return new WCFServiceClientChannel(this);
        }
        
        private class WCFServiceClientChannel : ChannelBase<PhoneApp1.OwlSecureServiceReference.IWCFService>, PhoneApp1.OwlSecureServiceReference.IWCFService {
            
            public WCFServiceClientChannel(System.ServiceModel.ClientBase<PhoneApp1.OwlSecureServiceReference.IWCFService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDBInitialize(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("DBInitialize", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDBInitialize(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DBInitialize", _args, result);
            }
            
            public System.IAsyncResult BeginLoadAllItemFromDatabase(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("LoadAllItemFromDatabase", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoItem> EndLoadAllItemFromDatabase(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoItem> _result = ((System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoItem>)(base.EndInvoke("LoadAllItemFromDatabase", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLoadAllCategoryFromDatabase(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("LoadAllCategoryFromDatabase", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoCategory> EndLoadAllCategoryFromDatabase(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoCategory> _result = ((System.Collections.ObjectModel.ObservableCollection<PhoneApp1.OwlSecureServiceReference.ToDoCategory>)(base.EndInvoke("LoadAllCategoryFromDatabase", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeleteToDoItem(PhoneApp1.OwlSecureServiceReference.ToDoItem toDoForDelete, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = toDoForDelete;
                System.IAsyncResult _result = base.BeginInvoke("DeleteToDoItem", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDeleteToDoItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DeleteToDoItem", _args, result);
            }
            
            public System.IAsyncResult BeginAddToDoItem(PhoneApp1.OwlSecureServiceReference.ToDoItem newToDoItem, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = newToDoItem;
                System.IAsyncResult _result = base.BeginInvoke("AddToDoItem", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAddToDoItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AddToDoItem", _args, result);
            }
            
            public System.IAsyncResult BeginSaveChangesToDB(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("SaveChangesToDB", _args, callback, asyncState);
                return _result;
            }
            
            public void EndSaveChangesToDB(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("SaveChangesToDB", _args, result);
            }
        }
    }
}
